class Dominostester{
public static void main (String deliveryofthefood[]){
System.out.println("welcome to Dominos");
String foodname = "marghreta pizza";
double foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
double foodpricewithquantitiy = Dominos.search(foodname,2);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);

foodname = "cheese n tomatopizza";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,12);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "double cheese pizza";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,22);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "fresh veggie";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,23);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "peppy paneer pizza";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,4);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "veggie paradise";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,6);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "veg extravaganza";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,2);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "cheese dominator";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,5);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "4 cheese pizza";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,8);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "deluxe veggie pizza";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,2);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "paneer makhani";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,7);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "indi tandoori";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,2);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "achari";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,8);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "pepper barbecue pizza";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,7);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "pepper barbecue pizza chiken";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,2);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "pepper barbecue pizza veg";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,7);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "pepper barbecue family pizza";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,6);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "pepper barbecue onion pizza";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,2);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "chicken golden delight pizza";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,62);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
foodname = "non veg supreme pizza";
foodprice = Dominos.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquantitiy = Dominos.search(foodname,2);
System.out.println("price of food with qqqquantityy is  " + foodpricewithquantitiy);
System.out.println("thank you enjoyy the food");
}
}