class Kfctester{
public static void main (String deliveryofthefood[]){
System.out.println("welcome to KFC");
String foodname = "5leg pc & 2 dips bucket";
double foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
double foodpricewithquanti = Kfc.search(foodname,6);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);


foodname = "peri peri 10pcs";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,16);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);

foodname = "peri peri 4pcs";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,26);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);

foodname = "classic chicken roll";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,4);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "double chicken roll";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,5);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "double chiken roll meal for 1";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,3);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "mini chiken roll";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,5);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "classic chiken rool meal for 2";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,6);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "2 classic chiken roll";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,67);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "2 double chiken roll";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,8);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "the allu arjun combo";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,9);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "buket for two";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,6);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "stay home buket";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,5);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "peri peri 10 leg";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,9);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "peri peri 5leg";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,8);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "big 12";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,5);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "ultimate saving bucket";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,6);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "big 8";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,3);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "5pc smoky red chiken";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,6);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "mingles bucket meal";
foodprice = Kfc.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Kfc.search(foodname,7);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
System.out.println("thank you enjoyy the food");
}
}