class  Pizzahuttester{
public static void main (String deliveryofthefood[]){
System.out.println("welcome to  Pizzahut");
String foodname = "triple pizza";
double foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
double foodpricewithquanti =  Pizzahut.search(foodname,7);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);

foodname = "triple treat box";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,17);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "triple treat box non veg";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,27);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "triple treat box pure veg";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,7);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "family fun meal 1";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,11);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "family fun meal 2";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,2);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "family fun meal 5";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,3);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "big pizza meal 2";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,4);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "big pizza meal 3";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,5);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "big pizza meal";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,5);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "magic pizza box";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,6);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "magic pizza box 1";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,7);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "magic pizza box non veg";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,8);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "magic pizza box 7";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,9);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "personal pan pizza";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,7);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "personal pan pizza 2";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,9);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "personal pan pizza non veg";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,5);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "personal pan pizza veg";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,6);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "big pizza";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,7);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
foodname = "small pizza";
foodprice =  Pizzahut.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti =  Pizzahut.search(foodname,8);
System.out.println("price of food with quantity is  " +  foodpricewithquanti);
System.out.println("thank you enjoyy the food");
}
}