class Swiggytester{
public static void main (String deliveryofthefood[]){
System.out.println("welcome to Swiggy");
String foodname = "french fry";
double foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
double foodpricewithquanti = Swiggy.search(foodname,3);
System.out.println("price of food with quantityis  " + foodpricewithquanti);

foodname = "papaya milkshake";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,2);
System.out.println("price of food with quantityis  " + foodpricewithquanti);

foodname = "frtesh fruit";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,11);
System.out.println("price of food with quantityis  " + foodpricewithquanti);

foodname = "classic buttermilk";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,3);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "oreo milk shake";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,5);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "fresh lemon juice";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,2);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "badam milk";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,5);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "bannana milkshake";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,6);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "pine apple juice";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,7);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "pepper juice";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,6);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "water melon juice";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,8);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "bisleri";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,3);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "tea";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,2);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "ginger tea";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,3);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "black tea";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,4);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "elaichi";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,6);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "desi tea";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,8);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "butter roti";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,9);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "rotti";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,3);
System.out.println("price of food with quantityis  " + foodpricewithquanti);
foodname = "chhole bhature";
foodprice = Swiggy.search(foodname);
System.out.println("price of food is  " + foodprice);
foodpricewithquanti = Swiggy.search(foodname,6);
System.out.println("price of food with quantityis  " + foodpricewithquanti);


System.out.println("thank you enjoyy the food");
}
}